config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :category, required: true
  has_many :reviews

  scope :by_category, -> (category_name) {
                        joins(:category)
                        .where(categories: { name: category_name })
                        .order('created_at DESC')
                      }

  has_attached_file :book_img,
                    styles: { book_index: "250x350>", book_show: "325x475>" },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

  def average_review
    reviews.empty? ? 0 : reviews.average(:rating).round(2)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
# BooksController
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update]

  def index
    if params[:category].blank?
      @books = Book.all.order('created_at DESC')
    else
      @books = Book.by_category(params[:category])
    end
  end

  def show
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to root_url
  end

  private

    def book_params
      params.require(:book).permit(:title, :description, :author, :category_id,
                                   :book_img)
    end

    def find_book
      @book = Book.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to @book
  end

  private

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_book
      @book = Book.find(params[:book_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.association :category, prompt: 'Select a Category', label: false %>
  <%= f.input :book_img, label: false %>
  <%= f.input :title, label: 'Book Title' %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit, class: 'btn-custom2' %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.empty? %>
  <h1>There are no books currently in this category</h1>
<% else %>

  <div class="row row-centered">
    <% @books.each do |book| %>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <%= link_to book do %>
          <%= image_tag book.book_img.url(:book_index), class: 'book img-responsive' %>
        <% end %>
      </div>
    <% end %>
<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-book-form">
    <h1>New Book</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show), class: 'book-show' %>
  </div>
  <div class="col-md-8">
    <div class="book-info">
      <div class="links btn-group" style="float: right">
        <%= link_to 'Back', root_path, class: 'btn btn-custom' %>
        <% if @book.user == current_user %>
        <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-custom' %>
        <%= link_to 'Delete', @book, method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'btn btn-custom' %>
        <% end %>
      </div>
      <h2 class="book-title"><%= @book.title %></h2>
      <h3 class="book-author"><span>From</span> <%= @book.author %></h3>
      <h4 class="average-rating">Average Rating</h4>
      <div class="review-rating" data-score="<%= @book.average_review %>"></div>
      <span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>
      <p class="book-desc"><%= @book.description %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <%= link_to 'Add Review', new_book_review_path(@book),
                  class: 'btn btn-custom btn-add-review' %>
      <h1>Reviews</h1>
      <div class="row">
        <%= render @book.reviews %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">

  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Book Review', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Add Book', new_book_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name,
                            books_path(category: category.name), class: 'link' %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <% unless notice.blank? %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <% unless alert.blank? %>
  <p class="alert"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @review]) do |f| %>
  <div id="rating-form" data-score="<%= @review.rating %>">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, class: 'btn-custom2' %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review col-md-3">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>

  <% if @book.user == current_user %>
    <div class="links btn-group">
      <%= link_to 'Edit', edit_book_review_path(review.book, review),
                  class: 'btn btn-custom' %>
      <%= link_to 'Delete', book_review_path(review.book, review), method: :delete,
                  data: { confirm: 'Are you sure?' }, class: 'btn btn-custom' %>
    </div>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-review-form">
    <h1>Edit Review</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-review-form">
    <h1>New Review</h1>
    <%= render 'form' %>
  </div>
</div>